import numpy as np
import torch
from concept_erasure import LeaceEraser

def main():
    print("Loading raw activations...")
    # Load the arrays generated by extract.py
    X_all_np = np.load("X_Domain_A.npy")
    y_all_np = np.load("y_Domain_A.npy")
    
    # concept_erasure operates on PyTorch tensors, so we convert them
    # We use float32 for stable mathematical operations
    X_all = torch.tensor(X_all_np, dtype=torch.float32)
    
    # ---------------------------------------------------------
    # 1. Isolate the "Other" (Control) Activations
    # ---------------------------------------------------------
    # Because of our strict quadruplet flattening in extract.py:
    # Index % 4 == 0 -> q1_self_harm
    # Index % 4 == 1 -> q2_self_benefit
    # Index % 4 == 2 -> q3_other_harm
    # Index % 4 == 3 -> q4_other_benefit
    
    total_rows = X_all.shape[0]
    
    # Extract indices for the control quadrants
    idx_other_harm = np.arange(2, total_rows, 4)
    idx_other_benefit = np.arange(3, total_rows, 4)
    
    X_other_harm = X_all[idx_other_harm]
    X_other_benefit = X_all[idx_other_benefit]
    
    # Combine them into a single tensor for fitting LEACE
    X_other = torch.cat([X_other_harm, X_other_benefit], dim=0)
    
    # ---------------------------------------------------------
    # 2. Create the Generic Sentiment Labels
    # ---------------------------------------------------------
    # 0 = Harm (Negative Sentiment), 1 = Benefit (Positive Sentiment)
    y_sentiment_harm = torch.zeros(X_other_harm.shape[0], dtype=torch.float32)
    y_sentiment_benefit = torch.ones(X_other_benefit.shape[0], dtype=torch.float32)
    
    Y_sentiment = torch.cat([y_sentiment_harm, y_sentiment_benefit], dim=0)
    
    print(f"Fitting LEACE on {X_other.shape[0]} 'Other' samples to isolate sentiment...")
    
    # ---------------------------------------------------------
    # 3. Fit LEACE and Scrub the Dataset
    # ---------------------------------------------------------
    # We fit the eraser ONLY on the "Other" data. This ensures it learns 
    # the generic sentiment axis without accidentally learning the "Self" axis.
    eraser = LeaceEraser.fit(X_other, Y_sentiment)
    
    # Now we apply the eraser to the ENTIRE dataset (Self + Other).
    # This subtracts the sentiment vector from all 600 rows.
    X_scrubbed = eraser(X_all)
    
    # Convert back to NumPy arrays and save
    X_scrubbed_np = X_scrubbed.detach().cpu().numpy()
    
    np.save("X_Domain_A_scrubbed.npy", X_scrubbed_np)
    
    print(f"Success! Scrubbed matrix saved with shape: {X_scrubbed_np.shape}")
    print("The dataset is now mathematically sterilized of sentiment confounders.")

if __name__ == "__main__":
    main()